name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Vérifier la présence de composer.json
      - name: List files in www
        run: |
          cd www
          ls -la
          
      # Étape 2 : Installer Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      # Étape 3 : Lancer les services Docker avec Docker Compose
      - name: Start Docker services
        run: docker-compose up -d --build

      # Étape 4 : Attendre que MySQL soit prêt
      - name: Wait for MySQL
        run: |
          until docker exec arcadia_studi_mysql_1 mysqladmin ping -h"localhost" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      # Étape 5 : Installer les dépendances Composer
      - name: Install Composer dependencies
        run: |
          cd www
          composer install --no-progress --prefer-dist --no-interaction

      # Étape 6 : Exécuter les tests PHPUnit depuis le répertoire spécifié
      - name: Run PHPUnit tests
        run: |
          chmod +x ../vendor/bin/phpunit  # Rendre le fichier exécutable
          cd tests  # Naviguer dans le répertoire des tests
          ../vendor/bin/phpunit --configuration ../phpunit.xml --colors=always


      # Étape 7 : Exécuter les tests PHPUnit depuis le répertoire spécifié
      - name: Run PHPUnit tests
        run: |
          cd www/tests
          ../vendor/bin/phpunit --configuration ../phpunit.xml --colors=always
