name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Installer Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      # Étape 3 : Lancer les services Docker avec Docker Compose
      - name: Start Docker services
        run: docker-compose up -d --build

      # Étape 4 : Attendre que MySQL soit prêt
      - name: Wait for MySQL
        run: |
          until docker exec mysql_container mysqladmin ping -h"localhost" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      # Étape 5 : Exécuter PHPUnit dans le conteneur PHP/Apache
      - name: Run PHPUnit tests
        run: docker exec php_apache_container vendor/bin/phpunit --configuration phpunit.xml --colors=always
